baseURL = "https://blog.uplinkoutlaw.com"
title = "Uplink Outlaw - Niche Tech Articles"
themesDir = "../.."

[pagination]
pagerSize = 8

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[params]
author = "YuePlush"
description = "Artist, but really tech nerd"
avatar = "/uploads/crab-rave.gif"
menu_item_separator = " - "

[[params.social]]
icon = "brand-github"
name = "My Portal Sites"
url = "https://www.yueplush.com"

[[params.social]]
icon = "brand-mastodon"
name = "Fediverse(Sharkey)"
url = "https://cradle-hub.yueplush.com/@yueplushalt"

[module]

[[module.imports]]
path = "github.com/vaga/hugo-theme-m10c"
